A = float(input("Введите значение A: "))
B = float(input("Введите значение B: "))
C = float(input("Введите значение C: "))
result = 4 * (B / 3.14) + (C * 3 + 5)
print("Результат выражения 4°(B/3,14)+(C*3 + 5) равен:", result)